# Generated by Django 6.0.2 on 2026-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('publicacao', models.CharField(max_length=4)),
                ('quantidade', models.IntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
