# Generated by Django 6.0.2 on 2026-03-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='publicacao',
            new_name='ano_lancamento',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='quantidade',
            new_name='quantidade_total',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
